# Generated by Django 4.2.10 on 2026-02-25 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_groups_alter_user_user_permissions_and_more'),
        ('services', '0002_rolecategorypermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='authentication.business', verbose_name='Negocio'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_categories', to='authentication.business', verbose_name='Negocio'),
        ),
    ]
