# Generated by Django 4.2.10 on 2025-06-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_calendar_id',
            field=models.CharField(blank=True, help_text='ID del calendario de Google del empleado', max_length=200, null=True),
        ),
    ]
