# Generated by Django 4.2.10 on 2026-04-09 02:37

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_groups_alter_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL del logo'),
        ),
        migrations.AddField(
            model_name='business',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='business',
            name='working_days',
            field=models.JSONField(default=authentication.models.default_working_days, verbose_name='Días hábiles'),
        ),
        migrations.AddField(
            model_name='user',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='Porcentaje de comisión (%)'),
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('start_time', models.TimeField(verbose_name='Hora de entrada')),
                ('end_time', models.TimeField(verbose_name='Hora de salida')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Horario de trabajo',
                'verbose_name_plural': 'Horarios de trabajo',
                'unique_together': {('employee', 'day_of_week')},
            },
        ),
    ]
