# Generated by Django 4.2.10 on 2025-06-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, help_text='ID del evento en Google Calendar', max_length=200, null=True),
        ),
    ]
