# Generated by Django 4.2.10 on 2026-02-25 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_groups_alter_user_user_permissions_and_more'),
        ('appointments', '0002_appointment_google_calendar_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='authentication.business', verbose_name='Negocio'),
        ),
    ]
